### PR TITLE
New GDB options.

### PR DESCRIPTION
**Pull request by Nucleoprotein**
Needs review/testing. Do not merge until!

### CODE REVIEW

**Comment by Nucleoprotein** [comment]
Anyone tested if this works ?

**Comment by Nucleoprotein** [comment]
Rebased.

**Comment by Nucleoprotein** [comment]
@Squall-Leonhart 
@EJocys

**Comment by Squall-Leonhart** [comment]
i don't use scripthook, so i can't really test this myself :x

**Comment by bull29** [comment]
Any chance this can be merged? It's extremely annoying being unable to use multiple controllers with v

**Pull request closed without merging**
